using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using ClearPlan.Core.Review;

namespace ClearPlan.Core.Tests
{
    internal static class Program
    {
        [STAThread]
        private static int Main(string[] args)
        {
            if (args.Length >= 2 &&
                args[0].Equals("RefDbContract", StringComparison.OrdinalIgnoreCase))
            {
                return RefDbContractTests.Run(args[1]);
            }

            if (args.Length >= 1 &&
                args[0].Equals(
                    "ExportScenarios",
                    StringComparison.OrdinalIgnoreCase))
            {
                return SyntheticScenarioTests.ExportScenarios(
                    args.Length >= 2 ? args[1] : null);
            }

            if (args.Length >= 2 &&
                args[0].Equals(
                    "ValidateSnapshot",
                    StringComparison.OrdinalIgnoreCase))
            {
                return ValidateExternalSnapshot(args[1]);
            }

            string filter = args.FirstOrDefault() ?? string.Empty;
            var tests = new List<TestCase>
            {
                new TestCase("ReviewLanguage.EnglishGermanRoundTrip", ReviewLanguageTests.EnglishGermanRoundTrip),
                new TestCase("ReviewLanguage.LiveBindingsAndReportScope", ReviewLanguageTests.LiveBindingsAndReportScope),
                new TestCase("ReviewLanguage.AllViewsAndPlotIdentity", ReviewLanguageTests.AllViewsAndPlotIdentity),
                new TestCase("ReviewLanguage.ExplicitBilingualLabelScopes", ReviewLanguageTests.ExplicitBilingualLabelScopes),
                new TestCase("ReviewLanguage.GuiSelectorRoundTripPreservesIdentity", ReviewLanguageTests.GuiSelectorRoundTripPreservesIdentity),
                new TestCase("ReviewLanguage.HtmlAndPdfLanguageRoundTripPreservesClinicalValues", ReviewLanguageTests.HtmlAndPdfLanguageRoundTripPreservesClinicalValues),
                new TestCase("IsodoseDisplay.DefaultsValidation", IsodoseDisplayTests.DefaultsAndValidation),
                new TestCase("CtCompatibility.ExactTuple", CtCompatibilityTests.ApprovedExactTuple),
                new TestCase("CtCompatibility.WrongTuple", CtCompatibilityTests.WrongTupleNeverPasses),
                new TestCase("CtCompatibility.MissingDisabled", CtCompatibilityTests.MissingDisabledAndUnconfiguredNeverPass),
                new TestCase("CtCompatibility.Invalid", CtCompatibilityTests.InvalidConfigurationNeverPasses),
                new TestCase("CtCompatibility.LegacyBoundary", CtCompatibilityTests.LegacyBoundaryIsExact),
                new TestCase("CtCompatibility.Settings", CtCompatibilityTests.SettingsIntegration),
                new TestCase("CtCompatibility.NativeGui", CtCompatibilityTests.NativeAndGuiIntegration),
                new TestCase("CtCompatibility.VersionReload", CtCompatibilityTests.VersionHistoryAndReload),
                new TestCase("IsodoseDisplay.RealDetachedLevels", IsodoseDisplayTests.PlaneLevelsAreRealAndDetached),
                new TestCase("IsodoseDisplay.GuiExport", IsodoseDisplayTests.GuiEditsAndExportUseSamePalette),
                new TestCase("IsodoseDisplay.Settings", IsodoseDisplayTests.SettingsPathAndValidation),
                new TestCase("IsodoseDisplay.RenderScale", IsodoseDisplayTests.RenderedScaleShowsOnlyPresentLevels),
                new TestCase("ReportPresentation.StableTitleVersion", ReportPresentationTests.StableTitleAndVersionReplaceDecorativeWarningBanners),
                new TestCase("BevCollimatorDisplay.LayerColorsMaximumField", BevCollimatorDisplayTests.PhysicalLayersUseGreenAndBlueWithExplicitMaximumField),
                new TestCase("AriaMetadata.Detached", AriaReportUploadTests.ClinicalMetadataIsDetachedAndExact),
                new TestCase("AriaMetadata.Native", AriaReportUploadTests.NativeAuthorComesFromEsapiAndIsDisclosed),
                new TestCase("AriaMetadata.AuthorLookup", AriaFhirClientTests.InteractiveAuthorExactLookup),
                new TestCase("AriaMetadata.Readback", AriaFhirClientTests.ClinicalMetadataReadbackCannotAcceptServiceAuthor),
                new TestCase("AriaMetadata.LegacyUploadGuard", AriaFhirClientTests.UnboundLegacyRequestCannotBeUploaded),
                new TestCase("CollisionSweepUI.Playback", CollisionSweepInteractionTests.PlaybackStepsCachedFramesAndStopsAtTheEnd),
                new TestCase("CollisionSweepUI.BodyOnlyMinimum", CollisionSweepInteractionTests.BodyOnlyClearAndMinimumStartRemainScoped),
                new TestCase("CollisionSweepUI.FixedRoomReference", CollisionSweepInteractionTests.RoomReferenceHasFixedStandAndTurnsOnlyPatientAxis),
                new TestCase("CollisionSweep.Contract", CollisionSweepTests.DetachedContractExists),
                new TestCase("ReviewDvh.FixedAxes", ReviewDvhInteractionTests.ReviewComparisonAndParameterAxesStayFixed),
                new TestCase("ReviewDvh.LegacyFixedAxes", ReviewDvhInteractionTests.LegacyNativeDvhAxesStayFixed),
                new TestCase("ReportPresentation.DvhWrappedLegend", ReportPresentationTests.DvhLegendWrapsBelowAndRetainsEverySeries),
                new TestCase("ReportPresentation.DvhPanels", ReportPresentationTests.PdfPaginatesEveryDvhCurveWithReadableLegends),
                new TestCase("CollisionSweep.ModelAssurance", CollisionSweepTests.ModelSeparationDoesNotChangeClinicalAssurance),
                new TestCase("CollisionSweepUI.CrossFieldRepeat", CollisionSweepInteractionTests.PlaybackCrossesFieldsAndCanRepeat),
                new TestCase("CollisionSweepUI.MlcIdentity", CollisionSweepInteractionTests.MlcInsetKeepsCapturedCpIdentityAndClearsMissingData),
                new TestCase("CollisionSweepUI.StaticPause", CollisionSweepInteractionTests.PlaybackPauseRemainsAvailableOnStaticField),
                new TestCase("CollisionSweepUI.MlcFreshness", CollisionSweepInteractionTests.MlcInsetRejectsChangedIsocenterAndNativeGeometryStamp),
                new TestCase("CollisionSweepUI.MlcRender", CollisionSweepInteractionTests.ApertureInsetUsesPhysicalLayersWithoutDrr),
                new TestCase("CollisionSweep.ArcSampling", CollisionSweepTests.ArcOrderEndpointsAndStaticDeduplication),
                new TestCase("CollisionSweep.AmbiguousArcs", CollisionSweepTests.AmbiguousOrInconsistentArcsStayUncertain),
                new TestCase("CollisionSweep.CoverageCoordinates", CollisionSweepTests.CoverageAndCoordinateGatesPreserveProofs),
                new TestCase("CollisionSweep.SourceDistances", CollisionSweepTests.SourceSignedDistancesAreNominalAndConservative),
                new TestCase("CollisionSweep.TrianglesHalcyon", CollisionSweepTests.TriangleInteriorsAndHalcyonRoleDistances),
                new TestCase("CollisionSweep.ProfilesBoundsCancellation", CollisionSweepTests.ProfileDistancesAndWorkloadCancellation),
                new TestCase("CollisionSweep.StationaryBoreBudget", CollisionSweepTests.StationaryBoreReusesGeometryWithoutDroppingArcStates),
                new TestCase("CollisionSweep.SpatialBoundsLimits", CollisionSweepTests.SpatialPruningKeepsBoundsAndHonorsLimits),
                new TestCase("CollisionSweep.OpenBoreRadial", CollisionSweepTests.OpenBoreRadialReviewSeparatesCapturedClearanceFromClinicalAssurance),
                new TestCase("CollisionSweepUI.Context", CollisionSweepInteractionTests.ContextChangesStopPlaybackAndClearExportFrames),
                new TestCase("CollisionSweepUI.View", CollisionSweepInteractionTests.ViewIncludesPlaybackGhostsAndStatusDistanceTable),
                new TestCase("CollisionSweepUI.NativeCoverage", CollisionSweepInteractionTests.NativeCoverageComesFromTheImageNotTheReportCrop),
                new TestCase("CollisionSweepUI.NativeLayout", CollisionSweepInteractionTests.NativeLayoutKeepsLargeViewport),
                new TestCase("CollisionSweepUI.StableCamera", CollisionSweepInteractionTests.PlaybackRetainsTheRoomCamera),
                new TestCase("CollisionSweepUI.RadialWorstPose", CollisionSweepInteractionTests.WorstPoseUsesDisplayedRadialDistance),
                new TestCase("CollisionCtCoverage.ImageBounds", CollisionCtCoverageTests.ImageBoundsDetectCappedExternalAndInvalidMetadata),
                new TestCase("CollisionSweepReport.PerBeam", CollisionSweepReportTests.ReportGetsEachBeamOverviewStatusAndDistances),
                new TestCase("CollisionSweepReport.OrientationStrip", CollisionSweepReportTests.OrientationStripIsSeparateBoundToMinimumAndDetached),
                new TestCase("CollisionSweepUI.AngleCircles", CollisionSweepInteractionTests.BothAngleCirclesClearAndHalcyonNeverShowsCArm),
                new TestCase("CollisionSweepReport.Unavailable", CollisionSweepReportTests.UnavailableSweepDoesNotExportAnEmptyOverview),
                new TestCase("SourceCollision.Contract", SourceCollisionScreeningTests.SeparateContractExists),
                new TestCase("SourceCollision.Catalog", SourceCollisionScreeningTests.CatalogPreservesUnitsProvenanceAndExactBinding),
                new TestCase("SourceCollision.RejectCatalog", SourceCollisionScreeningTests.CatalogRejectsAmbiguousMalformedAndCommissioningClaims),
                new TestCase("SourceCollision.MillimetresTangency", SourceCollisionScreeningTests.TrueBeamUsesMillimetresAndIncludesTangency),
                new TestCase("SourceCollision.NativeDirection", SourceCollisionScreeningTests.TrueBeamNativeDirectionAndTranslationsDeterminePose),
                new TestCase("SourceCollision.ReachScope", SourceCollisionScreeningTests.ReachAndSampleScopeCannotClaimClearance),
                new TestCase("SourceCollision.Halcyon", SourceCollisionScreeningTests.HalcyonUsesSourceRadiiLeadingLimitsAndExternalOnly),
                new TestCase("SourceCollision.InvalidInputs", SourceCollisionScreeningTests.MissingInvalidNonNativeAndUnsupportedInputsAreUnavailable),
                new TestCase("SourceCollision.Cancellation", SourceCollisionScreeningTests.CancellationNeverReturnsScreeningSuccess),
                new TestCase("SourceCollision.PublishedModels", SourceCollisionScreeningTests.DisabledCatalogAndPublishedSourceAreExplicit),
                new TestCase("SourceCollision.NativeWorkload", SourceCollisionScreeningTests.NativeWorkloadIsExplicitBoundedAndCancellableInFlight),
                new TestCase("SourceCollision.NumericalAndOutputBounds", SourceCollisionScreeningTests.RotatedTangencyAndResultSizeAreBounded),
                new TestCase("SourceCollision.IdentityAndCoverage", SourceCollisionScreeningTests.DuplicateIdentitiesFailAndMissingSurfaceRolesAreDisclosed),
                new TestCase("CollisionIntegration.SettingsAndMemoryBoundary", CollisionIntegrationTests.SettingsAndMemoryBoundary),
                new TestCase("CollisionIntegration.HeadlessIllustration", CollisionIntegrationTests.HeadlessIllustrationUsesTheGuiSceneWithoutAWindow),
                new TestCase("CollisionIntegration.SourceModelIllustration", CollisionIntegrationTests.SourceModelIllustrationDoesNotInventCoordinateConfirmation),
                new TestCase("CollisionIntegration.ReloadInvalidation", CollisionIntegrationTests.ReloadInvalidatesOldGeometryAndIllustration),
                new TestCase("CollisionIntegration.ReportIllustrationIsOptInAndDetached", CollisionIntegrationTests.ReportIllustrationIsOptInAndDetached),
                new TestCase("Collision.CoreContract", CollisionTests.CoreContractExists),
                new TestCase("Collision.SphereTriangleDistance", CollisionTests.SphereTriangleInteriorEdgesAndVertices),
                new TestCase("Collision.SphereContainment", CollisionTests.SphereContainmentTangencyAndMargin),
                new TestCase("Collision.SphereAnalyticSweep", CollisionTests.SphereAnalyticBoxSweepAndTranslation),
                new TestCase("Collision.CollapsedTriangles", CollisionTests.NumericallyCollapsedTrianglesCannotYieldClear),
                new TestCase("Collision.ContainmentEdgeRays", CollisionTests.ContainmentEdgeRaysAndHollowComponents),
                new TestCase("Collision.RingTangency", CollisionTests.RingTangencyTranslationAndPartialCoverage),
                new TestCase("Collision.RingClipping", CollisionTests.RingClipsTrianglesToFiniteAxialSlab),
                new TestCase("Collision.MissingInvalidInputs", CollisionTests.MissingUncommissionedAndInvalidInputsFailClosed),
                new TestCase("Collision.TopologyAndBounds", CollisionTests.MeshTopologyNumericsAndWorkloadFailClosed),
                new TestCase("Collision.ExactProfiles", CollisionTests.ProfilesAreBoundedExactAndEvidenceGated),
                new TestCase("Collision.SyntheticAndCancellation", CollisionTests.CancellationAndSyntheticLimitations),
                new TestCase("Collision.WorkloadAndCancellation", CollisionTests.WorkloadLimitAndInFlightCancellation),
                new TestCase("BevCollimator.Registration", BevCollimatorDisplayTests.CalibratedRasterAndApertureStayRegisteredAtZeroNinetyAndThirtyDegrees),
                new TestCase("BevCollimator.UnknownCalibration", BevCollimatorDisplayTests.UnknownCalibrationNeverGuessesFromCollimatorAngle),
                new TestCase("BevCollimator.Ruler", BevCollimatorDisplayTests.NumericRulerAnnotationsAreRemovedButIsoAndTicksRemain),
                new TestCase("BevCollimator.Jaws", BevCollimatorDisplayTests.PhysicalJawValuesFollowRotatedMidpointsAndJawlessHasNoJaws),
                new TestCase("BevCollimator.CalibrationCopy", BevCollimatorDisplayTests.SyntheticFactoriesAndSnapshotPreserveDisplayCalibration),
                new TestCase("BevCollimator.CTLandmark", BevCollimatorDisplayTests.ProjectedWorldLandmarkRemainsUprightAcrossCollimatorAngles),
                new TestCase("SyntheticPublication.Contract", SyntheticPublicationScenarioTests.FactoryContract),
                new TestCase("SyntheticPublicationIntegration.Catalog", SyntheticPublicationIntegrationTests.ScenarioCatalogAndCliAgree),
                new TestCase("SyntheticPublicationIntegration.Images", SyntheticPublicationIntegrationTests.SuppliedImagesSurviveGuiAndReport),
                new TestCase("SyntheticPublicationIntegration.Drr", SyntheticPublicationIntegrationTests.RegeneratedDrrRemainsCoherent),
                new TestCase("SyntheticPublicationIntegration.CaptureCt", SyntheticPublicationIntegrationTests.CtTabIsAvailableToAutomation),
                new TestCase("SyntheticPublicationIntegration.Provenance", SyntheticPublicationIntegrationTests.ReportsDescribeSharedPhantomAccurately),
                new TestCase("SyntheticPublication.Deterministic", SyntheticPublicationScenarioTests.DeterministicAndSynthetic),
                new TestCase("SyntheticPublication.NumericGoals", SyntheticPublicationScenarioTests.GoalsAndQualityUseDisplayedDvh),
                new TestCase("SyntheticPublication.SharedPhantom", SyntheticPublicationScenarioTests.ThreePlanesUseSamePhantomDose),
                new TestCase("SyntheticPublication.LayerAndRate", SyntheticPublicationScenarioTests.LayersPamAndEstimatedDoseRate),
                new TestCase("SyntheticPublication.BevAndTarget", SyntheticPublicationScenarioTests.BeamViewsUsePhantomAndTarget),
                new TestCase("AriaConnection.Configuration", AriaConnectionTests.ConfigurationContract),
                new TestCase("AriaConnection.DurableReceipts", AriaConnectionTests.DurableUploadReceipts),
                new TestCase("AriaConnection.InMemoryReport", AriaConnectionTests.InMemoryReportForUpload),
                new TestCase("AriaConnection.BoundedFileWork", AriaConnectionTests.CanceledFileWorkReleasesLateLease),
                new TestCase("AriaFhir.Contract", AriaFhirClientTests.Contract),
                new TestCase("AriaAction.PatientBound", ReviewWorkspaceHostControllerTests.AriaActionIsPatientBoundAndDisabledInSandbox),
                new TestCase("AriaOAuth.Contract", AriaOAuthTests.Contract),
                new TestCase("AriaOAuth.Protocol", AriaOAuthTests.Protocol),
                new TestCase("AriaOAuth.Cancellation", AriaOAuthTests.Cancellation),
                new TestCase("AriaOAuth.Rejections", AriaOAuthTests.Rejections),
                new TestCase("AriaFhir.PatientExact", AriaFhirClientTests.PatientExact),
                new TestCase("AriaFhir.PatientPagination", AriaFhirClientTests.PatientPagination),
                new TestCase("AriaFhir.Provider", AriaFhirClientTests.Provider),
                new TestCase("AriaFhir.Terminology", AriaFhirClientTests.Terminology),
                new TestCase("AriaFhir.UriBoundary", AriaFhirClientTests.UriBoundary),
                new TestCase("AriaFhir.BoundedFailures", AriaFhirClientTests.BoundedFailures),
                new TestCase("AriaFhir.UploadOnce", AriaFhirClientTests.UploadOnce),
                new TestCase("AriaFhir.UploadUncertain", AriaFhirClientTests.UploadUncertain),
                new TestCase("AriaFhir.SafeBusinessRules", AriaFhirClientTests.SafeBusinessRuleRejections),
                new TestCase("AriaFhir.CreateReferenceRecovery", AriaFhirClientTests.CreateReferenceRecovery),
                new TestCase("AriaFhir.EmptyCreatedLocation", AriaFhirClientTests.CreatedEmptyBodyWithAriaLocation),
                new TestCase("AriaFhir.ResponseTargetRecovery", AriaFhirClientTests.UnexpectedResponseTargetRetainsOnlyTrustedRecoveryLocation),
                new TestCase("AriaFhir.ReadbackTimestamps", AriaFhirClientTests.ReadbackTimestampIntegrity),
                new TestCase("AriaFhir.SparseFileReadback", AriaFhirClientTests.SparseFileReadback),
                new TestCase("AriaAttachment.RootBoundary", AriaAttachmentReaderTests.ConfigurationAndPathBoundary),
                new TestCase("AriaAttachment.BlockBeforeAccess", AriaAttachmentReaderTests.BlockBeforeFileAccess),
                new TestCase("AriaAttachment.LocalReadGuards", AriaAttachmentReaderTests.LocalFileAndReparseGuards),
                new TestCase("AriaFhir.Verification", AriaFhirClientTests.Verification),
                new TestCase("AriaFhir.Cancellation", AriaFhirClientTests.Cancellation),
                new TestCase("AriaFhir.SlowDependencyCancellation", AriaFhirClientTests.SlowDependencyCancellation),
                new TestCase("AriaFhir.TerminologyIntegrity", AriaFhirClientTests.TerminologyIntegrity),
                new TestCase("AriaFhir.PageLimitAndPreflight", AriaFhirClientTests.PageLimitAndUploadPreflight),
                new TestCase("AriaConnection.InvalidConfig", AriaConnectionTests.InvalidConfigurations),
                new TestCase("AriaConnection.Credentials", AriaConnectionTests.ExternalCredentials),
                new TestCase("AriaConnection.CertificatePin", AriaConnectionTests.CertificateBinding),
                new TestCase("AriaUpload.Contract", AriaReportUploadTests.ExposesDetachedBuilderContract),
                new TestCase("AriaUpload.PayloadRoundTrip", AriaReportUploadTests.PayloadRoundTripsExactBytesAndFingerprint),
                new TestCase("AriaUpload.ImmutableRequest", AriaReportUploadTests.RequestAndPayloadMutationsCannotChangePreparedBytes),
                new TestCase("AriaUpload.PatientBinding", AriaReportUploadTests.ExactPatientBindingHasNoNormalizationOrBypass),
                new TestCase("AriaUpload.References", AriaReportUploadTests.ReferencesRejectAbsoluteQueriesControlsAndTraversal),
                new TestCase("AriaUpload.PdfGate", AriaReportUploadTests.PdfGateRejectsMissingWrongAndOversizedData),
                new TestCase("AriaUpload.PreliminaryProfile", AriaReportUploadTests.PayloadUsesInstalledPreliminaryProfileWithoutInventedIdentity),
                new TestCase("AriaUpload.UtcTimestamp", AriaReportUploadTests.TimestampIsCallerSuppliedUtcInstant),
                new TestCase("AriaUpload.DocumentDateConfig", AriaReportUploadTests.DocumentDateConfiguration),
                new TestCase("AriaUpload.DocumentDatePolicy", AriaReportUploadTests.DocumentDatePolicyIsPureAndBounded),
                new TestCase("AriaUpload.DocumentDatePayload", AriaReportUploadTests.DocumentDateNeverChangesAttachmentCreation),
                new TestCase("AriaUpload.DocumentDateGui", AriaReportUploadTests.NativeDocumentDateDisclosure),
                new TestCase("AriaUpload.SafeText", AriaReportUploadTests.TitleAndDescriptionAreConciseAndNeverRawPaths),
                new TestCase("AriaUpload.Terminology", AriaReportUploadTests.ResolvedTerminologyAndPlanBindingAreMandatory),
                new TestCase("AriaUpload.SanitizedErrors", AriaReportUploadTests.ValidationErrorsAreSanitizedAndCarryNoInnerException),
                new TestCase("AriaUpload.DotSegments", AriaReportUploadTests.DotSegmentsCannotBecomeRelativePatientOrProviderTargets),
                new TestCase("AriaUpload.UnicodeAndDrivePaths", AriaReportUploadTests.UnicodeLineBreaksAndDriveRelativePathsAreRejected),
                new TestCase("ConstraintSelection.MostDistinctHits", ConstraintTableSelectorTests.MostDistinctHitsWinWithinMatchingFractions),
                new TestCase("ConstraintSelection.AliasHits", ConstraintTableSelectorTests.AliasesCountWithoutOverridingFractionOrConfirmation),
                new TestCase("ConstraintSelection.OneHitPerRequest", ConstraintTableSelectorTests.AConstraintCannotCountCanonicalAndLegacyIdTwice),
                new TestCase("TargetQuality.ScalarDefinitions", TargetQualityTests.ScalarDefinitionsAndMissingValues),
                new TestCase("TargetQuality.AvailabilityDisplay", TargetQualityTests.AvailabilityReflectsValuesAndPreservesWarnings),
                new TestCase("TargetQuality.CoverageBounds", TargetQualityTests.CoverageMustBeFiniteAndWithinNativeRange),
                new TestCase("TargetQuality.TargetRecognition", TargetQualityTests.TargetRecognitionIsConsistentAndPamFailsClosed),
                new TestCase("TargetQuality.GuiReportReadOnly", TargetQualityTests.SyntheticGuiAndReportShareTheSameMetrics),
                new TestCase("MappingSafety.NoDicomFallback", StructureMappingSafetyTests.UnmatchedOrgansNeverUseBroadDicomTypes),
                new TestCase("MappingSafety.AmbiguousCandidates", StructureMappingSafetyTests.AmbiguousAliasesNeverChooseTheFirstCandidate),
                new TestCase("MappingSafety.AmbiguousDefinitions", StructureMappingSafetyTests.AmbiguousDefinitionsNeverChooseTheFirstDefinition),
                new TestCase("MappingSafety.ExplicitAliasAndCode", StructureMappingSafetyTests.ExplicitAliasesAndCodesStillResolve),
                new TestCase("MappingSafety.AvailabilityLabels", StructureMappingSafetyTests.MappingAvailabilityIsNotGoalAchievement),
                new TestCase("MappingSafety.LegacyPath", StructureMappingSafetyTests.LegacyMappingUsesTheSameFailClosedResolver),
                new TestCase("NativeLayout.Header", NativeReviewLayoutTests.HeaderFitsClinicalAndSandboxContent),
                new TestCase("NativeLayout.Legend", NativeReviewLayoutTests.DvhLegendIsOutsideOnTheRight),
                new TestCase("NativeLayout.PlanSwitch", NativeReviewLayoutTests.NativePlanSwitchUsesTheExistingReadOnlyReplacement),
                new TestCase("NativeLayout.NominalWithoutGeometry", NativeReviewLayoutTests.ParameterPlotsKeepNominalValueWithoutGeometry),
                new TestCase("NativeLayout.VisibleParameterSamples", NativeReviewLayoutTests.ParameterPlotsUseRealIndicesAndVisibleMarkers),
                new TestCase("NativeLayout.ParameterAvailability", NativeReviewLayoutTests.ParameterPlotsExposeUnavailableAndChangedBeamState),
                new TestCase("NativeLayout.PaddickNaming", NativeReviewLayoutTests.ReciprocalConformityUsesPaddickNaming),
                new TestCase("DvhInteraction.NativeReset", ReviewDvhInteractionTests.ClinicalResetUsesDetachedWorkspaceOnly),
                new TestCase("ReviewControls.Reference", ReviewControlTests.ReferenceSelectionIsSeparateFromOpening),
                new TestCase("PlanCheckSelection.Grouping", PlanCheckSelectionTests.RepeatedLegacyCodesAreGroupedWithoutHidingWarnings),
                new TestCase("PlanCheckSelection.Invalid", PlanCheckSelectionTests.MissingAndInvalidConfigurationPreserveFindings),
                new TestCase("PlanCheckSelection.Privacy", PlanCheckSelectionTests.ConfigurationContainsOnlyCodesAndFlags),
                new TestCase("PlanCheckSelection.Integration", PlanCheckSelectionTests.SettingsAndVersionedReviewIntegrationExist),
                new TestCase("ReviewControls.Visibility", ReviewControlTests.ExplicitTargetVisibilityAndRefreshAreShared),
                new TestCase("ReviewControls.Unmatched", ReviewControlTests.HideUnmatchedLeavesMappingAndUnavailableMatches),
                new TestCase("NativeLayout.PlannedRateOnly", NativeReviewLayoutTests.ParameterRatePlotsUseOnlyAvailablePlannedSamples),
                new TestCase("ReviewControls.CompactLayout", ReviewControlTests.CompactChecksAndClickableLegendsAreWired),
                new TestCase("PamBest.Default95", PamBestTargetTests.DefaultPtvRuleUsesStrict95PercentOnly),
                new TestCase("PamBest.Automatic", PamBestTargetTests.AutomaticSelectionWaitsForAllPtvCandidates),
                new TestCase("PamBest.Lowest", PamBestTargetTests.LowestCompletePamWinsAndTiesAreDeterministic),
                new TestCase("PamBest.Incomplete", PamBestTargetTests.MissingNonfiniteAndIncompletePamNeverWin),
                new TestCase("PamBest.Explicit", PamBestTargetTests.ExplicitSelectionRemainsAuthoritative),
                new TestCase("PamBest.Native", PamBestTargetTests.NativeAutomaticWorkflowPreservesDetachedMlcGeometry),
                new TestCase("HtmlReport.CompactOptions", HtmlReportTests.CompactOptionsKeepUnavailabilityAndDoNotMutateData),
                new TestCase("HtmlReport.StartOnly", HtmlReportTests.BeamViewsUseExactStartOrStayCompactlyUnavailable),
                new TestCase("ReportPresentation.Options", ReportPresentationTests.ReportOptionsFilterOnlyTheRenderedEvidence),
                new TestCase("ReportPresentation.PamSelection", ReportPresentationTests.PamSelectionCountsAreCompactAndExplicit),
                new TestCase("ReportPresentation.EmptyTargetQuality", ReportPresentationTests.MissingTargetQualityDoesNotReserveAnEmptyPage),
                new TestCase("DvhInteraction.BatchedReset", ReviewDvhInteractionTests.ResetBatchesRedrawAndRestoresAxesWithoutReplacingModels),
                new TestCase("DvhInteraction.BulkSelection", ReviewDvhInteractionTests.BulkSelectionRefreshesOnceAndKeepsRequiredTargets),
                new TestCase("DvhInteraction.Controllers", ReviewDvhInteractionTests.BothPlotViewsBindIndependentHoverControllers),
                new TestCase("DvhInteraction.Hover", ReviewDvhInteractionTests.HoverShowsStructureDoseAndVolumeWithoutMouseDown),
                new TestCase("Quicklook.Action", QuicklookIntegrationTests.ActionIsSeparateAndUnsubscribed),
                new TestCase("PlanImagesWorkspace.DetachedPlanes", PlanImagesWorkspaceTests.RunAll),
                new TestCase("TargetClassification.DerivedOrgans", TargetClassificationTests.DerivedOrganNamesAreNotAutomaticTargets),
                new TestCase("TargetClassification.IntentionalNames", TargetClassificationTests.IntentionalNamesRemainRecognized),
                new TestCase("TargetClassification.NativeTypes", TargetClassificationTests.NativeTypesRemainAuthoritative),
                new TestCase("TargetClassification.DvhPam", TargetClassificationTests.DvhAndPamDoNotPromoteOrganExclusions),
                new TestCase("HtmlReport.Sections", HtmlReportTests.AllSectionsAndDoseStatisticsArePresent),
                new TestCase("HtmlReport.Encoding", HtmlReportTests.HostileTextCannotBecomeMarkupOrAttributes),
                new TestCase("HtmlReport.Goals", HtmlReportTests.GoalsOmitReferencesButKeepResultAndMapping),
                new TestCase("HtmlReport.Unavailable", HtmlReportTests.MissingAndNonfiniteValuesRemainUnavailable),
                new TestCase("HtmlReport.SelfContained", HtmlReportTests.OutputHasNoExternalDependencies),
                new TestCase("HtmlReport.Targets", HtmlReportTests.CurrentPlanAndRequiredTargetsAreNotLost),
                new TestCase("HtmlReport.Images", HtmlReportTests.ImagesAreEmbeddedOnlyFromAvailableDetachedPixels),
                new TestCase("HtmlReport.Utf8", HtmlReportTests.NullInputAndUtf8ExportAreExplicit),
                new TestCase("HtmlReport.AllCurves", HtmlReportTests.EverySelectedCurveHasAChartPanel),
                new TestCase("HtmlReport.AllBeams", HtmlReportTests.EveryCachedBeamHasAnImagePanel),
                new TestCase("HtmlReport.Companion", HtmlReportTests.CompanionExportNeverOverwritesExistingFiles),
                new TestCase("HtmlReport.Bounds", HtmlReportTests.ExtremeFiniteCurvesAreWithheldAndMetricScopeIsVisible),
                new TestCase("Feedback.StatusSeverity", ReviewFeedbackPresentationTests.StatusColorsFollowExplicitSeverity),
                new TestCase("Feedback.CompletionLimitations", ReviewFeedbackPresentationTests.CompletedAnalysisKeepsLimitationsVisible),
                new TestCase("Feedback.DvhTrackerContrast", ReviewFeedbackPresentationTests.BothDvhTrackersUseOpaqueHighContrastTemplate),
                new TestCase("BevCompactStatus", BevCompactStatusTests.RunAll),
                new TestCase("Quicklook.CapturedData", QuicklookIntegrationTests.NativeQuicklookUsesCapturedDataAndPrivacy),
                new TestCase("Quicklook.InApp", QuicklookIntegrationTests.PreviewIsInAppAndBlocksNavigation),
                new TestCase("BevActivation", BevActivationTests.RunAll),
                new TestCase("ConfigurationWorkspace.EditsAndHistory", ConfigurationWorkspaceTests.RunAll),
                new TestCase("ConfigurationHistory.Import", ConfigurationHistoryTests.ImportKeepsExternalSourceAndRecordsMetadata),
                new TestCase("ConfigurationHistory.Restore", ConfigurationHistoryTests.EditsAndRestoreAppendHistory),
                new TestCase("ConfigurationHistory.Conflict", ConfigurationHistoryTests.RejectsStaleWritesAndUntrackedChanges),
                new TestCase("ConfigurationHistory.Validation", ConfigurationHistoryTests.RejectsUnsafeNamesBoundsAndInvalidContent),
                new TestCase("ConfigurationHistory.Integrity", ConfigurationHistoryTests.RefusesCorruptHistoryAndPreservesCurrent),
                new TestCase("ConfigurationHistory.Transaction", ConfigurationHistoryTests.FailedCommitRollsBackAndLockBlocksOtherWriters),
                new TestCase("ConfigurationHistory.Interrupted", ConfigurationHistoryTests.InterruptedAndMalformedHistoryFailsClosed),
                new TestCase("ConfigurationHistory.MalformedMetadata", ConfigurationHistoryTests.MetadataValidationRejectsNullRowsWithoutUnexpectedErrors),
                new TestCase("ConfigurationHistory.Activation", ConfigurationHistoryTests.ReadsDoNotCreateAStoreAndActivationPinsARevision),
                new TestCase("ConfigurationHistory.TemporaryFiles", ConfigurationHistoryTests.TemporaryFilesAreBoundedAndConfined),
                new TestCase("TargetReview.Contract", DvhSelectionPolicyTests.RequiredTargetsHaveASeparateSelectionContract),
                new TestCase("TargetReview.TargetKinds", DvhSelectionPolicyTests.NativeTargetKindsAndAliasesAreRecognized),
                new TestCase("TargetReview.LargestOverall", DvhSelectionPolicyTests.KeepsAllPtvsAndOnlyLargestContainedInnerTargetOverall),
                new TestCase("TargetReview.StrictRxSafety", DvhSelectionPolicyTests.TargetRulesKeepStrictBoundaryAndUnknownPrescriptionVisible),
                new TestCase("TargetReview.NativeIntegration", DvhSelectionPolicyTests.NativeTargetReviewIsReadOnlyAndSharedWithReport),
                new TestCase("TargetReview.EditableDefaultContract", DvhSelectionPolicyTests.DefaultRulesHaveAnEditableExternalConfiguration),
                new TestCase("TargetReview.EditDisableDelete", DvhSelectionPolicyTests.DefaultRuleEditsDisablesAndDeletionAreHonoredWithoutFallback),
                new TestCase("TargetReview.RequiredUiReport", DvhSelectionPolicyTests.RequiredTargetsSurviveUiAndReportSelectionAndNativeD98),
                new TestCase("BevWorkspace.Navigation", BevWorkspaceTests.ExposesControlPointNavigationAndExplicitDrrAction),
                new TestCase("BevWorkspace.Normalization", BevWorkspaceTests.NormalizationIsDescriptiveAndMissingIsNotZero),
                new TestCase("BevWorkspace.Privacy", BevWorkspaceTests.RejectsClinicalDrrInSyntheticSnapshot),
                new TestCase("BevWorkspace.ProfilePath", BevWorkspaceTests.MachineProfilePathRoundTripsIni),
                new TestCase("DrrProjection.AnalyticAndSynthetic", DrrProjectionTests.RunAll),
                new TestCase("NativeMlcProfile.Geometry", NativeMlcProfileTests.RunAll),
                new TestCase("NativeMlcFileSource.Utf8", NativeMlcFileSourceTests.ValidUtf8Json),
                new TestCase("NativeMlcFileSource.Paths", NativeMlcFileSourceTests.MissingAndInaccessiblePaths),
                new TestCase("NativeMlcFileSource.Bounds", NativeMlcFileSourceTests.BoundedStrictUtf8),
                new TestCase("NativeMlcFileSource.CancellationTimeout", NativeMlcFileSourceTests.CancellationAndTimeout),
                new TestCase("EsapiBev.ReadOnlyContract", EsapiBevContractTests.RunAll),
                new TestCase("GeometryFingerprint.Freshness", GeometryFingerprintTests.RunAll),
                new TestCase("BevRendering.Pixels", BeamEyeViewRenderingTests.PngDimensionsAndSyntheticMarker),
                new TestCase("BevRendering.PhysicalScale", BeamEyeViewRenderingTests.PhysicalWidthsAndIsocenterScaleAreExplicit),
                new TestCase("BevRendering.OrientationHeading", BeamEyeViewRenderingTests.OrientationSymbolsDoNotTouchTheirHeading),
                new TestCase("BevRendering.OrientationFooter", BeamEyeViewRenderingTests.OrientationFootnoteStaysClearOfTheSyntheticBanner),
                new TestCase("BevRendering.CollimatorInset", BeamEyeViewRenderingTests.CollimatorAngleChangesOnlyItsOwnSchematic),
                new TestCase("BevRendering.IndependentAngles", BeamEyeViewRenderingTests.ThreeOrientationAnglesVaryIndependently),
                new TestCase("BevRendering.CollimatorAxes", BeamEyeViewRenderingTests.CollimatorCardinalAndObliqueAxesRemainUnambiguous),
                new TestCase("BevRendering.AngleWraparound", BeamEyeViewRenderingTests.OrientationWraparoundIsEquivalentForAllAxes),
                new TestCase("BevRendering.MissingAngles", BeamEyeViewRenderingTests.MissingOrientationAnglesDoNotHideTheOtherAxes),
                new TestCase("BevRendering.ZeroReferences", BeamEyeViewRenderingTests.OrientationKeepsFixedZeroReferencesAndNumericLabels),
                new TestCase("BevRendering.CompactOrientation", BeamEyeViewRenderingTests.OrientationSurvivesMissingDrrAndCompactOutput),
                new TestCase("BevRendering.CalibratedCollimatorInset", BeamEyeViewRenderingTests.CalibratedCollimatorAxesFollowTheValidatedScreenRotation),
                new TestCase("BevRendering.RejectedCollimatorCalibration", BeamEyeViewRenderingTests.RejectedOrMissingCalibrationNeverControlsTheCollimatorInset),
                new TestCase("ReportPresentation.CtPages", ReportPresentationTests.CtSectionsHaveDedicatedPages),
                new TestCase("ReportFooter.PatientIdentity", ReportPresentationTests.PatientIdentityIsInTheRepeatingFooter),
                new TestCase("ReportFooter.BodyClearance", ReportPresentationTests.PaginatedTablesStayAboveTheThreeLineFooter),
                new TestCase("ReportFooter.Privacy", ReportPresentationTests.PatientFooterKeepsSyntheticAndPseudonymContextsSeparate),
                new TestCase("ReportFooter.Legacy", ReportPresentationTests.LegacyReportAlsoRepeatsPatientIdentity),
                new TestCase("ReportFooter.Headless", ReportPresentationTests.HeadlessIdentityIsAttachedOnlyForThePrivatePdf),
                new TestCase("ReportFooter.GuiRoute", ReportPresentationTests.GuiReportButtonsUseTheCurrentWorkspace),
                new TestCase("ReportFooter.ManuscriptSandbox", ReportPresentationTests.ManuscriptSandboxHidesTheNativeContext),
                new TestCase("ReportFooter.SyntheticCtOrientation", ReportPresentationTests.SyntheticCtBannerDoesNotCoverOrientation),
                new TestCase("ReportPresentation.SixSources", ReportPresentationTests.SixSourcesFitTheSummaryPage),
                new TestCase("PqmNumeric.CulturesAndUnits", PqmNumericEvaluatorTests.RunAll),
                new TestCase("ReviewDvhStatistics.All", ReviewDvhStatisticsTests.RunAll),
                new TestCase("PlanImageOverlays.All", PlanImageOverlayTests.RunAll),
                new TestCase("NativeWarnings.Source", NativeWarningsTests.SeparateSourceAndNoInferredApproval),
                new TestCase("ReportPresentation.MissingPqm", ReportPresentationTests.MissingPqmIsVisibleInsteadOfAnEmptyHeader),
                new TestCase("ReportPresentation.PqmSources", ReportPresentationTests.PqmSourcesAreGroupedAndMatchesStayVisible),
                new TestCase("ReportPresentation.CompactChecks", ReportPresentationTests.PlanCheckFindingsUseTheAvailableSpace),
                new TestCase("ReportPresentation.CtLegend", ReportPresentationTests.CtLegendDescribesContinuousSegmentOverlays),
                new TestCase("ReportPresentation.UnknownLayers", ReportPresentationTests.UnknownPhysicalLayersAreNotPresentedAsOne),
                new TestCase("BevRendering.Context", BeamEyeViewRenderingTests.RejectsDrrControlPointOrAngleMismatch),
                new TestCase("BevRendering.Jawless", BeamEyeViewRenderingTests.JawlessNeverLabelsVirtualBoundsAsJaws),
                new TestCase("BevRendering.Orientation", BeamEyeViewRenderingTests.CardinalGantryOrientationDoesNotDependOnCouch),
                new TestCase("BevRendering.Source", BeamEyeViewRenderingTests.SyntheticFactorySourceAndUnavailablePixelsAreGated),
                new TestCase("BevRendering.Layers", BeamEyeViewRenderingTests.DrrOpeningStaysVisibleAndBothMlcLayersAreOutlined),
                new TestCase("CapturePixels.RejectBlank", CapturePixelValidatorTests.RejectsTransparentAndSolidCaptures),
                new TestCase("CapturePixels.AcceptContent", CapturePixelValidatorTests.AcceptsOpaqueVariedCapturePixels),
                new TestCase("BevWorkspace.SyntheticMetadata", BevWorkspaceTests.SyntheticMetadataIsExplicitAndReported),
                new TestCase("DoseRateEstimator.Contract", DoseRateEstimatorTests.ContractExists),
                new TestCase("DoseRateEstimator.GantryAndMuLimits", DoseRateEstimatorTests.GantryAndMuLimits),
                new TestCase("DoseRateEstimator.ConstantMuLimited", DoseRateEstimatorTests.ConstantMuLimitedTraceIsValid),
                new TestCase("DoseRateEstimator.CmwAndPlannedSeparation", DoseRateEstimatorTests.CmwNormalizationAndPlannedValuesStaySeparate),
                new TestCase("DoseRateEstimator.WrapAndZeroIntervals", DoseRateEstimatorTests.WrapDirectionAndZeroIntervals),
                new TestCase("DoseRateEstimator.InvalidInputs", DoseRateEstimatorTests.InvalidInputsFailAtomically),
                new TestCase("DoseRateEstimator.RepeatedApply", DoseRateEstimatorTests.RepeatedApplyClearsStaleResults),
                new TestCase("DoseRateEstimator.FiniteOutputs", DoseRateEstimatorTests.FiniteOutputsAndOverflow),
                new TestCase("DoseRateEstimator.ExactProfileMatching", DoseRateEstimatorTests.ProfileMatchingIsExactAndSpecific),
                new TestCase("DoseRateEstimator.UnavailableProfiles", DoseRateEstimatorTests.MissingAmbiguousInvalidProfilesAreUnavailable),
                new TestCase("DoseRateEstimator.ProfileJson", DoseRateEstimatorTests.ProfileJsonValidationIsStrictAndSanitized),
                new TestCase("DoseRateEstimator.FileSource", DoseRateEstimatorTests.OptionalFileSourceIsBoundedAndSanitized),
                new TestCase("DoseRateEstimator.ExtremePrecision", DoseRateEstimatorTests.ExtremePrecisionFailsClosed),
                new TestCase("DoseRateEstimator.TinyDirection", DoseRateEstimatorTests.TinyIntervalsRetainDirection),
                new TestCase("PlanAnalysis.Contract", PlanAnalysisTests.CalculationContractExists),
                new TestCase("PlanAnalysis.GeometryAndMu", PlanAnalysisTests.RunCalculations),
                new TestCase("PlanAnalysis.Synthetic", PlanAnalysisTests.SyntheticExamplesAreCalculatedAndVendorFree),
                new TestCase("PlanAnalysis.EsapiReadOnlyContract", PlanAnalysisTests.EsapiAdapterIsReadOnlyAndExplicitAboutMissingData),
                new TestCase("PlanAnalysis.ProjectionFrames", MeshTargetProjectionTests.AnalyticFramesAndPerspective),
                new TestCase("PlanAnalysis.MeshTriangleUnion", MeshTargetProjectionTests.TriangleUnionNotXorAndNoConvexHull),
                new TestCase("PlanAnalysis.ProjectedPam", MeshTargetProjectionTests.PlanPamUsesUnionRows),
                new TestCase("PlanAnalysis.NativeRotation", MeshTargetProjectionTests.NativeRotationUsesCoordinatesNotAngleGuess),
                new TestCase("PlanAnalysis.NativeRotationResampling", MeshTargetProjectionTests.NativeRotationAcceptsIndependentContourSampling),
                new TestCase("PlanAnalysis.Cancellation", MeshTargetProjectionTests.CancellationAndInvalidFramesAreExplicit),
                new TestCase("PlanAnalysis.DetachedCopy", PlanAnalysisTests.DetachedCopyPreservesPrivateGeometryWithoutSharing),
                new TestCase("Smoke.ConstraintSourceMode", SmokeTests.ConstraintSourceModeIsStable),
                new TestCase("ReviewComparison.Units", ReviewComparisonTests.PreservesUnitsMissingAndChangedGoals),
                new TestCase("ReviewComparison.Ambiguity", ReviewComparisonTests.RejectsAmbiguityMappingAndModeMixing),
                new TestCase("ReviewComparison.Session", ReviewComparisonTests.RetainsSessionReferenceAndClearsAcrossModes),
                new TestCase("ReviewComparison.Replacement", ReviewComparisonTests.RetainsReferenceAcrossReplacementHost),
                new TestCase("ReviewComparison.ReportContext", ReviewComparisonTests.RejectsUncommittedOrChangedPlanForReport),
                new TestCase("ReviewComparison.Missing", ReviewComparisonTests.MissingValuesRemainMissing),
                new TestCase("ReviewExtended.Privacy", ReviewComparisonTests.ValidatesExtendedPrivacyAndNumbers),
                new TestCase("PlanImages.Contract", PlanImageTests.ImageContractExists),
                new TestCase("PlanImages.IsocenterDoseViewport", PlanImageViewportTests.RunAll),
                new TestCase("PlanImages.CenteredLargerRendering", ReportPresentationTests.CtImageIsLargerAndItsIsocenterIsCentered),
                new TestCase("PlanImages.MaximumLegend", ReportPresentationTests.CtMaximumSupportedLegendRetainsOnePagePerPlane),
                new TestCase("ReportPresentation.TargetsFirst", ReportPresentationTests.DvhTableLeadsWithRequiredTargetsAndRetainsManualChoices),
                new TestCase("PlanImages.Synthetic", PlanImageTests.SyntheticImagesAreDeterministicAndMarked),
                new TestCase("PlanImages.Geometry", PlanImageTests.PhysicalGeometryRejectsObliqueAndOutsidePositions),
                new TestCase("PlanImages.ActiveOnly", PlanImageTests.ReportOnlyContainsActivePlanImagesAndDetachedPixels),
                new TestCase("ReportPresentation.Width", ReportPresentationTests.TablesUseAvailablePageWidth),
                new TestCase("ReportPresentation.Bev", ReportPresentationTests.RepresentativeBevUsesMiddleCompletePositiveMuSample),
                new TestCase("ReportPresentation.Gaps", ReportPresentationTests.TraceGapsAreNotConnected),
                new TestCase("ReportPresentation.Labels", ReportPresentationTests.ReportLabelsControlPointTracesAndSelectedBev),
                new TestCase("ReportPresentation.BevPagination", ReportPresentationTests.BeamStartPanelsStayWithinOnePagePerBeam),
                new TestCase("ReportPresentation.NoOverallApproval", ReportPresentationTests.ActivePlanHeaderDoesNotImplyApproval),
                new TestCase("ConstraintValueNormalizer.Comparators", ConstraintValueNormalizerTests.NormalizesComparators),
                new TestCase("ConstraintValueNormalizer.Units", ConstraintValueNormalizerTests.NormalizesUnits),
                new TestCase("ConstraintValueNormalizer.Decimals", ConstraintValueNormalizerTests.ParsesInvariantAndGermanDecimals),
                new TestCase("ConstraintValueNormalizer.Metrics", ConstraintValueNormalizerTests.NormalizesSupportedMetrics),
                new TestCase("ConstraintCatalogValidator.Direction", ConstraintCatalogValidatorTests.RejectsComparatorAgainstMetricDirection),
                new TestCase("ConstraintCatalogValidator.Identity", ConstraintCatalogValidatorTests.ReportsDuplicateAndMissingIdentities),
                new TestCase("RefDbJsonConstraintSource.SparseDetails", RefDbJsonConstraintSourceTests.SummaryRangesSurviveSparseDetails),
                new TestCase("RefDbJsonConstraintSource.Schema", RefDbJsonConstraintSourceTests.RejectsUnexpectedSchema),
                new TestCase("RefDbJsonConstraintSource.Active", RefDbJsonConstraintSourceTests.LoadsOnlyActiveEntitiesByDefault),
                new TestCase("RefDbJsonConstraintSource.Aliases", RefDbJsonConstraintSourceTests.RetainsAliasesAndSideAliases),
                new TestCase("RefDbJsonConstraintSource.Constraints", RefDbJsonConstraintSourceTests.JoinsAndNormalizesConstraints),
                new TestCase("StructureAliasResolver.Order", StructureAliasResolverTests.UsesDeterministicRuleOrder),
                new TestCase("StructureAliasConfiguration.Ambiguity", StructureAliasConfigurationTests.RejectsAmbiguousAndCrossSideAliases),
                new TestCase("StructureAliasConfiguration.Preserve", StructureAliasConfigurationTests.PreservesSourceIdentityAndClinicalValues),
                new TestCase("StructureAliasConfiguration.Import", StructureAliasConfigurationTests.RoundTripsJsonAndImportsExistingSources),
                new TestCase("StructureAliasConfiguration.Ini", StructureAliasConfigurationTests.PersistsOptionalPathInIni),
                new TestCase("StructureAliasConfiguration.Tg263Markers", StructureAliasConfigurationTests.PreservesTg263SemanticMarkers),
                new TestCase("StructureAliasConfiguration.Laterality", StructureAliasConfigurationTests.RejectsUnknownLaterality),
                new TestCase("StructureAliasConfiguration.BlockMissing", StructureAliasConfigurationTests.BlocksMissingOverridesWithoutChangingSource),
                new TestCase("StructureAliasConfiguration.Save", StructureAliasConfigurationTests.SavesOnlyAliasDocumentsAndKeepsBackup),
                new TestCase("StructureAliasConfiguration.PublicExample", StructureAliasConfigurationTests.PublicExampleKeepsThresholdsAndSeparatesOrgans),
                new TestCase("StructureAliasResolver.Laterality", StructureAliasResolverTests.ProtectsLeftAndRightLaterality),
                new TestCase("StructureAliasResolver.Expansion", StructureAliasResolverTests.ExpandsPairedButNotCombinedStructures),
                new TestCase("StructureAliasResolver.Raw", StructureAliasResolverTests.ResolvesMissingStructureIdFromRawName),
                new TestCase("StructureAliasResolver.Fallback", StructureAliasResolverTests.UsesCodeBeforeDicomTypeFallback),
                new TestCase("StructureAliasResolver.Ambiguity", StructureAliasResolverTests.ReportsAmbiguityInsteadOfChoosingArbitrarily),
                new TestCase("SyntheticDvhMetrics.Interpolation", SyntheticDvhMetricsTests.InterpolatesEndpointsAndMidpoints),
                new TestCase("SyntheticDvhMetrics.MeanDose", SyntheticDvhMetricsTests.IntegratesMeanDose),
                new TestCase("SyntheticDvhMetrics.Thresholds", SyntheticDvhMetricsTests.ClassifiesExactThresholdBoundaries),
                new TestCase("SyntheticDvhMetrics.Invalid", SyntheticDvhMetricsTests.RejectsInvalidCurvesAndRequests),
                new TestCase("ExcelConstraintSource.SharedStrings", ExcelConstraintSourceTests.LoadsSharedStringsAndUnicode),
                new TestCase("ExcelConstraintSource.Stock2024", ExcelConstraintSourceTests.StockCatalogLoadsAsConfirmableFallback),
                new TestCase("ExcelConstraintSource.Schema", ExcelConstraintSourceTests.ReportsMissingHeaders),
                new TestCase("ExcelConstraintSource.Relationships", ExcelConstraintSourceTests.ReportsDuplicateIdsAndBrokenRelationships),
                new TestCase("ConstraintCatalogService.AutomaticRefDb", ConstraintCatalogServiceTests.AutomaticUsesValidRefDbFirst),
                new TestCase("ConstraintCatalogService.AutomaticFallback", ConstraintCatalogServiceTests.AutomaticFallsBackToExcelWithWarning),
                new TestCase("ConstraintCatalogService.Explicit", ConstraintCatalogServiceTests.ExplicitModesNeverSilentlyFallback),
                new TestCase("ConstraintCatalogService.Blocked", ConstraintCatalogServiceTests.AutomaticBlocksWhenNoSourceIsUsable),
                new TestCase("ConstraintCatalogService.Paths", ConstraintCatalogServiceTests.ResolvesRelativeAndAbsolutePaths),
                new TestCase("ConstraintTableSelector.Prescription", ConstraintTableSelectorTests.PrescriptionLabelsDisambiguateButDoNotOverrideDose),
                new TestCase("ConstraintTableSelector.StockConfirmation", ConstraintTableSelectorTests.StockDefinitionsCanRequireExplicitConfirmation),
                new TestCase("ConstraintTableSelector.PrescriptionCode", ConstraintTableSelectorTests.AnchoredPrescriptionCodeMatchesConfiguredTableOnly),
                new TestCase("ConstraintTableSelector.Fractionation", ConstraintTableSelectorTests.ExactFractionationOutranksGenericTables),
                new TestCase("ConstraintTableSelector.Dose", ConstraintTableSelectorTests.DoseRangesRefineCompatibleCandidates),
                new TestCase("ConstraintTableSelector.PlanSum", ConstraintTableSelectorTests.PlanSumRequiresPlanSumTable),
                new TestCase("ConstraintTableSelector.Coverage", ConstraintTableSelectorTests.StructureCoverageCannotRescueIncompatibleFractionation),
                new TestCase("ConstraintTableSelector.Ambiguity", ConstraintTableSelectorTests.TiesRequireConfirmation),
                new TestCase("ConstraintTableSelector.LegacyNine", ConstraintTableSelectorTests.SelectsAllNineLegacyDefaults),
                new TestCase("PqmObjectiveMapper.Contract", PqmObjectiveMappingContractTests.MapsNormalizedConstraintToLegacyPqmContract),
                new TestCase("PqmObjectiveMapper.Fallbacks", PqmObjectiveMappingContractTests.SuppliesSafeIdentityFallbacks),
                new TestCase("PqmObjectiveMapper.Null", PqmObjectiveMappingContractTests.RejectsMissingConstraint),
                new TestCase("FieldNameSuggester.Basic", FieldNamingPreviewTests.NamesStaticAndArcFields),
                new TestCase("FieldNameSuggester.ConfiguredDefaults", FieldNamingPreviewTests.ConfiguredDefaultsPreserveEstablishedNamesAndIds),
                new TestCase("FieldNameSuggester.ConfiguredOrderTokens", FieldNamingPreviewTests.ConfiguredOrderTokensAndDuplicateDirectionAreApplied),
                new TestCase("FieldNameSuggester.ConfiguredSafeMissing", FieldNamingPreviewTests.InvalidMissingAndDisabledRulesNeverInferConformance),
                new TestCase("FieldNameSuggester.ConfigurationIni", FieldNamingPreviewTests.FieldNamingConfigurationPathRoundTripsIni),
                new TestCase("FieldNameSuggester.Couch", FieldNamingPreviewTests.InsertsCouchAngleBeforeDirection),
                new TestCase("FieldNameSuggester.CouchDuplicate", FieldNamingPreviewTests.KeepsCouchAnglePenultimateForDuplicateArcs),
                new TestCase("FieldNameSuggester.Duplicates", FieldNamingPreviewTests.AddsAttachedDuplicateSuffixes),
                new TestCase("FieldNameSuggester.Order", FieldNamingPreviewTests.UsesTreatmentOrderThenBeamNumber),
                new TestCase("FieldNameSuggester.Tolerance", FieldNamingPreviewTests.UsesHalfDegreeTolerance),
                new TestCase("FieldNameSuggester.PlanId", FieldNamingPreviewTests.UsesPlanIdForExpectedFieldIds),
                new TestCase("FieldNameSuggester.Prefix", FieldNamingPreviewTests.PreservesConformingPrefixFromCurrentFields),
                new TestCase("FieldNameSuggester.Status", FieldNamingPreviewTests.ReportsIdAndNameConformanceSeparately),
                new TestCase("DvhSelection.Exact", DvhSelectionPolicyTests.SelectsExactMappedStructures),
                new TestCase("DvhSelection.External", DvhSelectionPolicyTests.ExcludesExternalAndBodyContours),
                new TestCase("DvhSelection.Partial", DvhSelectionPolicyTests.ExcludesPartialHelpersButKeepsTargets),
                new TestCase("ClinicalReviewMapper.PlanCheck", ClinicalReviewValueMapperTests.MapsPlanCheckStatusAndSeverity),
                new TestCase("ClinicalReviewMapper.Pqm", ClinicalReviewValueMapperTests.MapsPqmStatusAndSeverity),
                new TestCase("ClinicalReviewMapper.StableIds", ClinicalReviewValueMapperTests.CreatesDeterministicUniqueStableIds),
                new TestCase("ClinicalReviewMapper.Decimals", ClinicalReviewValueMapperTests.ParsesInvariantAndGermanDecimals),
                new TestCase("ClinicalReviewMapper.Dose", ClinicalReviewValueMapperTests.ConvertsCentigrayToGray),
                new TestCase("ClinicalReviewMapper.MissingPlanDose", ClinicalReviewValueMapperTests.MissingPlanDoseDoesNotAbortOverview),
                new TestCase("ClinicalReviewMapper.Fields", ClinicalReviewValueMapperTests.MapsFieldConformance),
                new TestCase("ClinicalReviewMapper.Sanitization", ClinicalReviewValueMapperTests.SanitizesPathsAndDicomUids),
                new TestCase("ReviewWorkspaceHost.ActionsOnce", ReviewWorkspaceHostControllerTests.DispatchesVisibleActionsExactlyOnce),
                new TestCase("ReviewWorkspaceHost.RefreshFallback", ReviewWorkspaceHostControllerTests.KeepsLastGoodViewModelWhenRefreshFails),
                new TestCase("ReviewWorkspaceHost.Dispose", ReviewWorkspaceHostControllerTests.UnsubscribesActionsWhenDisposed),
                new TestCase("ReviewWorkspaceHost.SingularHint", ReviewWorkspaceHostControllerTests.UsesSingularHintLabelForOneVariation),
                new TestCase("ReviewWorkspaceHost.ModeSwitch", ReviewWorkspaceHostControllerTests.SwitchesBetweenClinicalAndSyntheticSnapshots),
                new TestCase("ReviewWorkspaceHost.NativeStartupIsolation", ReviewWorkspaceHostControllerTests.ClinicalHostDoesNotInheritLegacyPlotModelsBeforeLoading),
                new TestCase("ReviewSnapshot.ValidMinimal", ReviewSnapshotTests.AcceptsValidMinimalSnapshot),
                new TestCase("ReviewSnapshot.SchemaVersion", ReviewSnapshotTests.RejectsUnsupportedSchemaVersion),
                new TestCase("ReviewSnapshot.Synthetic", ReviewSnapshotTests.RejectsNonSyntheticSimulatorInput),
                new TestCase("ReviewSnapshot.DuplicateIds", ReviewSnapshotTests.RejectsDuplicateStableIds),
                new TestCase("ReviewSnapshot.ActivePlan", ReviewSnapshotTests.RejectsMissingActivePlan),
                new TestCase("ReviewSnapshot.StatusSeverity", ReviewSnapshotTests.RejectsInvalidStatusAndSeverity),
                new TestCase("ReviewSnapshot.FiniteDose", ReviewSnapshotTests.RejectsNonFiniteDose),
                new TestCase("ReviewSnapshot.DoseOrder", ReviewSnapshotTests.RequiresIncreasingDoseOrder),
                new TestCase("ReviewSnapshot.CumulativeVolume", ReviewSnapshotTests.RejectsIncreasingCumulativeVolume),
                new TestCase("ReviewSnapshot.StructureReference", ReviewSnapshotTests.RejectsMissingReferencedStructure),
                new TestCase("ReviewSnapshot.PublishSafeLabels", ReviewSnapshotTests.RejectsIdentityBearingClinicalContent),
                new TestCase("ReviewSnapshot.EmbeddedPrivateContent", ReviewSnapshotTests.RejectsEmbeddedPrivateContentAcrossAllTextSurfaces),
                new TestCase("ReviewSnapshot.GenericSyntheticText", ReviewSnapshotTests.AllowsGenericSyntheticTextAcrossTheContract),
                new TestCase("ReviewSnapshot.JsonRoundTrip", ReviewSnapshotTests.JsonRoundTripIsDeterministic),
                new TestCase("ReviewReportMapping.Sections", ReviewReportMappingTests.PreservesEveryReviewSectionAndUnit),
                new TestCase("ReviewReportMapping.Watermark", ReviewReportMappingTests.ForcesTheSyntheticSafetyMark),
                new TestCase("ReviewReportMapping.PdfSmoke", ReviewReportMappingTests.WritesASyntheticPdf),
                new TestCase("ReviewReportMapping.PdfContent", ReviewReportMappingTests.PopulatesMappedPdfTableCells),
                new TestCase("ReviewWindowSizePolicy.Matrix", ReviewWindowSizePolicyTests.MatchesTheResponsiveWorkAreaMatrix),
                new TestCase("ReviewWindowSizePolicy.Contract", ReviewWindowSizePolicyTests.ExposesTheWindowSizingContract),
                new TestCase("ReviewWindowSizePolicy.Invalid", ReviewWindowSizePolicyTests.RejectsInvalidWorkAreas),
                new TestCase("SyntheticScenario.Catalog", SyntheticScenarioTests.DeclaresExactCatalogAndExpectations),
                new TestCase("SyntheticScenario.RowsAndStatuses", SyntheticScenarioTests.MatchesExactRowsStatusesAndStructures),
                new TestCase("SyntheticScenario.DvhMonotonicity", SyntheticScenarioTests.ProducesValidMonotoneDvhCurves),
                new TestCase("SyntheticScenario.Determinism", SyntheticScenarioTests.SerializesByteIdentically),
                new TestCase("SyntheticScenario.VisibleFaults", SyntheticScenarioTests.ExposesVisibleDoseAndCheckFaults),
                new TestCase("SyntheticScenario.PqmDvhConsistency", SyntheticScenarioTests.PqmValuesAndStatusesMatchDvhCurves),
                new TestCase("SyntheticScenario.FieldAndMapping", SyntheticScenarioTests.UsesFieldNamerAndShowsMappingDeviation),
                new TestCase("SyntheticScenario.OptionalFallback", SyntheticScenarioTests.UsesNeutralOptionalFallbackOnly),
                new TestCase("SyntheticScenario.MixedReview", SyntheticScenarioTests.IntegratedMixedReviewCombinesVisibleFindings),
                new TestCase("SyntheticScenario.Provenance", SyntheticScenarioTests.ContainsSyntheticProvenanceOnly),
                new TestCase("SyntheticScenario.CheckedInJson", SyntheticScenarioTests.CheckedInJsonMatchesFactory),
                new TestCase("SimulatorArguments.Defaults", SimulatorArgumentsTests.UsesDocumentedDefaults),
                new TestCase("SimulatorArguments.ScenarioTab", SimulatorArgumentsTests.ParsesScenarioAndTab),
                new TestCase("SimulatorArguments.Capture", SimulatorArgumentsTests.ParsesSingleCapture),
                new TestCase("SimulatorArguments.CaptureAll", SimulatorArgumentsTests.ParsesCaptureAll),
                new TestCase("SimulatorArguments.LayoutProbe", SimulatorArgumentsTests.ParsesLayoutProbe),
                new TestCase("SimulatorArguments.LayoutProbeInvalid", SimulatorArgumentsTests.RejectsInvalidLayoutProbeRequests),
                new TestCase("SimulatorArguments.Invalid", SimulatorArgumentsTests.RejectsUnknownOrIncompleteValues),
                new TestCase("SimulatorArguments.Conflicts", SimulatorArgumentsTests.RejectsConflictingOrDuplicateValues),
                new TestCase("SimulatorArguments.OutputPaths", SimulatorArgumentsTests.RejectsUnsafeOrWrongOutputPaths),
                new TestCase("SimulatorOutputPaths.Repository", SimulatorOutputPathsTests.UsesRepositoryArtifactsReportDirectory),
                new TestCase("SimulatorOutputPaths.Portable", SimulatorOutputPathsTests.UsesPortableArtifactsReportDirectory),
                new TestCase("SimulatorOutputPaths.Network", SimulatorOutputPathsTests.RejectsNetworkExecutableDirectory),
                new TestCase("SimulatorOutputPaths.Dvh", SimulatorOutputPathsTests.UsesDeterministicLocalDvhExportPath),
                new TestCase("SimulatorVisibleActions.Events", SimulatorVisibleActionTests.CommandsRaiseEveryVisibleActionEvent),
                new TestCase("SimulatorVisibleActions.Reset", SimulatorVisibleActionTests.ResetRestoresInitialSelectionAndPlotVisibility),
                new TestCase("SimulatorVisibleActions.OpenPlan", SimulatorVisibleActionTests.OpenPlanStatusIdentifiesTheSyntheticActivePlan),
                new TestCase("SimulatorVisibleActions.Mapping", SimulatorVisibleActionTests.MappingPersistsIntoSnapshotAndReport),
                new TestCase("SimulatorVisibleActions.MappingInvalid", SimulatorVisibleActionTests.MappingRejectsUnknownChoicesWithoutMutation),
                new TestCase("SimulatorVisibleActions.DvhPng", SimulatorVisibleActionTests.DvhExportWritesALocalPng),
                new TestCase("SimulatorVisibleActions.DvhNetwork", SimulatorVisibleActionTests.DvhExportRejectsNetworkOutput),
                new TestCase("SettingsValidator.RequiredSource", SettingsValidatorTests.RequiresConfiguredSourceByMode),
                new TestCase("SettingsValidator.Extension", SettingsValidatorTests.ChecksSourceExtensionsAndReadability),
                new TestCase("SettingsValidator.Directories", SettingsValidatorTests.AcceptsWritableOperationalDirectories),
                new TestCase("PathSettingsIni.RoundTrip", PathSettingsIniTests.RoundTripsEveryConfiguredPath),
                new TestCase("PathSettingsIni.Legacy", PathSettingsIniTests.ReadsLegacyPathAliases),
                new TestCase("PathFailureClassifier.Index", PathFailureClassifierTests.RejectsCollectionIndexErrors),
                new TestCase("PathFailureClassifier.WrappedIo", PathFailureClassifierTests.RecognizesWrappedIoErrors),
                new TestCase("PqmDefaultReviewPolicy.Valid", PqmDefaultReviewPolicyTests.KeepsValidRowsVisible),
                new TestCase("PqmDefaultReviewPolicy.Partial", PqmDefaultReviewPolicyTests.IgnoresDelimitedPartialHelpers),
                new TestCase("PqmDefaultReviewPolicy.Unavailable", PqmDefaultReviewPolicyTests.UsesExplicitUnavailableStatusForNonTargets),
                new TestCase("WritablePathFallback.File", WritablePathFallbackTests.UsesLocalFileWhenConfiguredParentIsUnavailable),
                new TestCase("WritablePathFallback.Directory", WritablePathFallbackTests.KeepsConfiguredDirectoryWhenItIsWritable)
            };

            var selected = tests
                .Where(test => string.IsNullOrWhiteSpace(filter) ||
                               test.Name.IndexOf(filter, StringComparison.OrdinalIgnoreCase) >= 0)
                .ToList();

            if (selected.Count == 0)
            {
                Console.Error.WriteLine("No tests matched filter '{0}'.", filter);
                return 2;
            }

            int failures = 0;
            foreach (TestCase test in selected)
            {
                try
                {
                    test.Execute();
                    Console.WriteLine("PASS {0}", test.Name);
                }
                catch (Exception exception)
                {
                    failures++;
                    Console.Error.WriteLine("FAIL {0}: {1}", test.Name, exception.Message);
                }
            }

            Console.WriteLine("{0} tests, {1} failures", selected.Count, failures);
            return failures == 0 ? 0 : 1;
        }

        private static int ValidateExternalSnapshot(string path)
        {
            try
            {
                ReviewSnapshot snapshot = ReviewSnapshotJson.DeserializeUtf8(
                    File.ReadAllBytes(path));
                ReviewSnapshotValidationResult result =
                    ReviewSnapshotValidator.Validate(snapshot);
                foreach (ReviewSnapshotValidationIssue issue in result.Issues)
                {
                    Console.Error.WriteLine(
                        "{0} {1}: {2}",
                        issue.Code,
                        issue.Path,
                        issue.Message);
                }

                Console.WriteLine(
                    "External snapshot validation: {0} issue(s).",
                    result.Issues.Count);
                return result.IsValid ? 0 : 1;
            }
            catch (Exception error)
            {
                Console.Error.WriteLine(
                    "External snapshot validation failed: " + error.Message);
                return 2;
            }
        }

        private sealed class TestCase
        {
            public TestCase(string name, Action execute)
            {
                Name = name;
                Execute = execute;
            }

            public string Name { get; private set; }
            public Action Execute { get; private set; }
        }
    }
}
